import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#EEEEEE",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#202124",
  },
  resetButton: {
    padding: 8,
  },
  resetButtonText: {
    color: "#D93025",
    fontSize: 14,
    fontWeight: "600",
  },
  stepContainer: {
    flex: 1,
    padding: 20,
  },
  stepContainerCenter: {
    flex: 1,
    padding: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  stepTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#3C4043",
    marginBottom: 20,
  },
  button: {
    backgroundColor: "#1A73E8",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#1A73E8",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonDisabled: {
    backgroundColor: "#DADCE0",
    shadowOpacity: 0,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  listItem: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#F1F3F4",
  },
  itemName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#202124",
  },
  itemMac: {
    fontSize: 12,
    color: "#70757A",
    marginTop: 2,
  },
  itemDetail: {
    fontSize: 14,
    fontWeight: "500",
    color: "#1E8E3E",
  },
  emptyText: {
    textAlign: "center",
    color: "#70757A",
    marginTop: 40,
    fontSize: 15,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#5F6368",
    marginBottom: 12,
  },
  wifiList: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    maxHeight: 200,
    overflow: "hidden",
  },
  wifiItem: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F3F4",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  wifiItemActive: {
    backgroundColor: "#E8F0FE",
  },
  wifiName: {
    fontSize: 15,
    color: "#3C4043",
  },
  wifiNameActive: {
    fontWeight: "700",
    color: "#1A73E8",
  },
  wifiDetail: {
    fontSize: 12,
    color: "#70757A",
  },
  emptyWifiText: {
    padding: 20,
    textAlign: "center",
    color: "#9AA0A6",
    fontStyle: "italic",
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#3C4043",
    marginBottom: 8,
    marginTop: 12,
  },
  input: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#DADCE0",
    fontSize: 16,
    color: "#202124",
  },
  row: {
    flexDirection: "row",
    marginTop: 8,
  },
  provisionMainTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#202124",
    marginTop: 24,
    marginBottom: 32,
  },
  statusTracker: {
    width: "100%",
    paddingHorizontal: 30,
  },
  statusLine: {
    fontSize: 16,
    color: "#BDC1C6",
    marginBottom: 16,
    fontWeight: "500",
  },
  statusLineActive: {
    color: "#1A73E8",
    fontWeight: "700",
  },
  hintText: {
    marginTop: 40,
    color: "#70757A",
    fontSize: 14,
  },
  successIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#E6F4EA",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
  },
  successIconText: {
    fontSize: 40,
    color: "#1E8E3E",
    fontWeight: "700",
  },
  successTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#202124",
    marginBottom: 16,
  },
  uidDisplay: {
    backgroundColor: "#F1F3F4",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    marginBottom: 32,
    flexDirection: "row",
    alignItems: "center",
  },
  uidLabel: {
    fontSize: 14,
    color: "#5F6368",
    marginRight: 8,
  },
  uidValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#202124",
    fontFamily: "Courier",
  },
  doneDescription: {
    fontSize: 16,
    color: "#5F6368",
    textAlign: "center",
    lineHeight: 24,
    paddingHorizontal: 20,
    marginBottom: 40,
  },
  primaryButton: {
    backgroundColor: "#202124",
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 30,
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  debugContainer: {
    marginTop: 20,
    backgroundColor: "#F1F3F4",
    borderRadius: 12,
    padding: 12,
    flex: 1,
    width: "100%",
    borderWidth: 1,
    borderColor: "#EEEEEE",
  },
  debugHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  debugTitle: {
    color: "#5F6368",
    fontSize: 12,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  debugText: {
    color: "#3C4043",
    fontSize: 11,
    marginBottom: 4,
    fontFamily: "Courier",
  },
  debugList: {
    flex: 1,
  },
});
